### ISSUE TITLE
Unable to run brunch server

### ISSUE THREAD

**Issue by The-Batman-1998** [HubSpot/facewall#17]
Installed brunch
Ran npm install

Node ver: v0.12.6
Brunch v1.6.7

Keep getting this error. Please help!

"/Users/onooristani/Work/facewall/node_modules/javascript-brunch" does exist in the node_modules directory and has contents.

```
$ brunch watch --server -p 3333
/usr/local/lib/node_modules/brunch/lib/watch.js:446
          throw new Error("You probably need to execute `npm install` to insta
                ^
Error: You probably need to execute `npm install` to install brunch plugins. Error: Cannot find module '/Users/onooristani/Work/facewall/node_modules/javascript-brunch'
  at /usr/local/lib/node_modules/brunch/lib/watch.js:446:17
  at Array.map (native)
  at loadDeps (/usr/local/lib/node_modules/brunch/lib/watch.js:431:8)
  at loadPackages (/usr/local/lib/node_modules/brunch/lib/watch.js:451:13)
  at /usr/local/lib/node_modules/brunch/lib/watch.js:471:17
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:597:12
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:558:16
  at /usr/local/lib/node_modules/brunch/lib/helpers.js:507:12
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:263:16
  at /usr/local/lib/node_modules/brunch/node_modules/read-components/index.js:72:14
  at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
```

**Comment by 40x** [comment]
:+1: 
Getting same error

**Comment by henry-laney** [comment]
Same error.

Edit: This fix in package.json worked for me.

`
"dependencies": {
        "brunch": "^2.0.0",
        "javascript-brunch": "^2.0.0",
        "coffee-script-brunch": "^2.0.0",
        "css-brunch": "^2.0.0",
        "stylus-brunch": "^2.0.0",
        "handlebars-brunch": "^2.0.0",
        "uglify-js-brunch": "^2.0.0",
        "clean-css-brunch": "^2.0.0"
    }
`
